"""Admin configuration for inventory models."""

from django.contrib import admin
from django.utils.html import format_html

from .models import StockMovement, StockRecord


class StockMovementInline(admin.TabularInline):
    """Recent stock movements shown inline on StockRecord change page."""

    model = StockMovement
    extra = 0
    fields = ["movement_type", "quantity_change", "reference", "performed_by", "created_at"]
    readonly_fields = ["movement_type", "quantity_change", "reference", "performed_by", "created_at"]
    ordering = ["-created_at"]
    max_num = 20  # Only show recent 20 movements inline

    def has_add_permission(self, request, obj=None):
        return False

    def has_delete_permission(self, request, obj=None):
        return False


@admin.register(StockRecord)
class StockRecordAdmin(admin.ModelAdmin):
    """Admin for per-product stock levels with movement history inline."""

    inlines = [StockMovementInline]

    list_display = [
        "product",
        "quantity",
        "reserved_quantity",
        "available_quantity_display",
        "reorder_level",
        "reorder_status",
    ]
    list_filter = ["product__category", "product__status"]
    search_fields = ["product__name", "product__sku"]
    readonly_fields = ["available_quantity_display", "reorder_status", "created_at", "updated_at"]
    ordering = ["product__name"]

    fieldsets = (
        ("Product", {"fields": ("product",)}),
        (
            "Stock Levels",
            {
                "fields": (
                    "quantity",
                    "reserved_quantity",
                    "available_quantity_display",
                    "reorder_level",
                    "reorder_quantity",
                    "reorder_status",
                ),
            },
        ),
        ("Timestamps", {"fields": ("created_at", "updated_at"), "classes": ("collapse",)}),
    )

    @admin.display(description="Available")
    def available_quantity_display(self, obj):
        qty = obj.available_quantity
        color = "red" if qty <= obj.reorder_level else "green"
        return format_html('<span style="color:{};font-weight:bold;">{}</span>', color, qty)

    @admin.display(description="Reorder Needed", boolean=True)
    def reorder_status(self, obj):
        return obj.needs_reorder


@admin.register(StockMovement)
class StockMovementAdmin(admin.ModelAdmin):
    """
    Read-only audit log of all stock movements.

    Movements are never created or edited in admin — they are
    generated by the application (order fulfilment, returns, etc.).
    Staff can search and filter for audit purposes only.
    """

    list_display = [
        "created_at",
        "stock_record",
        "movement_type",
        "quantity_change",
        "reference",
        "performed_by",
    ]
    list_filter = ["movement_type", "created_at"]
    search_fields = [
        "stock_record__product__name",
        "stock_record__product__sku",
        "reference",
        "performed_by__email",
    ]
    readonly_fields = [
        "stock_record",
        "movement_type",
        "quantity_change",
        "reference",
        "notes",
        "performed_by",
        "created_at",
    ]
    ordering = ["-created_at"]
    date_hierarchy = "created_at"

    def has_add_permission(self, request):
        """Movements are created by the application, not manually."""
        return False

    def has_change_permission(self, request, obj=None):
        """Audit logs must never be edited."""
        return False

    def has_delete_permission(self, request, obj=None):
        """Audit logs must never be deleted."""
        return False
