# Generated by Django 5.2.14 on 2026-05-11 18:57

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was first created.'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='label',
            field=models.CharField(blank=True, help_text="Friendly name, e.g. 'Home', 'Office'.", max_length=100),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.'),
        ),
    ]
