# Generated by Django 4.2.30 on 2026-05-07 13:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was first created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.')),
                ('quantity', models.IntegerField(default=0, help_text='Current available quantity', validators=[django.core.validators.MinValueValidator(0)])),
                ('reserved_quantity', models.IntegerField(default=0, help_text='Quantity reserved by pending orders (not yet shipped)')),
                ('reorder_level', models.PositiveIntegerField(default=10, help_text='Alert when stock falls below this level')),
                ('reorder_quantity', models.PositiveIntegerField(default=50, help_text='How many to order when restocking')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='products.product')),
            ],
            options={
                'ordering': ['product__name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was first created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.')),
                ('movement_type', models.CharField(choices=[('RECEIVED', 'Stock Received'), ('SOLD', 'Sold (Order Fulfilled)'), ('RETURNED', 'Customer Return'), ('DAMAGED', 'Damaged/Write-off'), ('ADJUSTMENT', 'Manual Adjustment'), ('RESERVED', 'Reserved for Order'), ('UNRESERVED', 'Reservation Released')], max_length=20)),
                ('quantity_change', models.IntegerField(help_text='Positive = stock in, Negative = stock out')),
                ('reference', models.CharField(blank=True, help_text='Reference (e.g., order number, PO number)', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('stock_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.stockrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
