/**
 * Auto-generated TypeScript types from the Django OpenAPI schema.
 *
 * DO NOT EDIT this file by hand.
 *
 * Regenerate with:
 *   npm run gen-types
 *
 * Which runs:
 *   npx openapi-typescript http://localhost:8000/api/schema/ -o src/types/schema.d.ts
 *
 * Requires the Django dev server to be running:
 *   make up
 */

// Types will be generated here by openapi-typescript.
// Until then, use inline interfaces in each view/store.
export {};
