# Generated by Django 5.2.14 on 2026-05-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was first created.'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was first created.'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.'),
        ),
    ]
