# Generated by Django 5.2.14 on 2026-05-11 18:57

from django.db import migrations

import shopforge.apps.users.managers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', shopforge.apps.users.managers.UserManager()),
            ],
        ),
    ]
