#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

echo "Starting Celery worker..."
watchfiles \
    --filter python \
    'celery -A config.celery_app worker --loglevel=info -Q celery,high_priority,low_priority' \
    /app/shopforge/
