#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

echo "Starting Celery beat (periodic task scheduler)..."
celery -A config.celery_app beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
